# Generated by Django 3.1.2 on 2020-11-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20201103_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
