# Generated by Django 3.1.2 on 2020-11-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20201104_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['restaurant', 'type', 'name']},
        ),
        migrations.AlterField(
            model_name='restaurantbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.badge'),
        ),
        migrations.AlterField(
            model_name='restaurantbadge',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_badges', to='restaurants.restaurant'),
        ),
    ]
